name: Build and Deploy to Netlify without Netlify Build Time

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Install ImageMagick (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
    
      - name: Install ImageMagick (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install imagemagick
    
      - name: Install ImageMagick (Windows)
        if: runner.os == 'Windows'
        run: choco install imagemagick -y

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --dir=_site --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
